#!/usr/bin/env bash
# run nginx as nginx user not root user

nginx_conf="/etc/nginx/nginx.conf"
sed -i 's/#user www-data/user nginx/' "$nginx_conf"
sed -i 's/80/8080/g' "$nginx_conf"
chmod 644 /etc/nginx/nginx.conf
pkill apache
sudo -u nginx service nginx start
